FROM busybox:1.28

RUN mkdir /root/app
WORKDIR /root/app
SHELL ["/bin/sh","-c"]
ENV OLD_DISCOVERY_SERVER_VERIFY_DATA=<OLD_DISCOVERY_SERVER_VERIFY_DATA> \
    DISCOVERY_SERVER_VERIFY_DATA=<DISCOVERY_SERVER_VERIFY_DATA> \
    OLD_PPROF_VERIFY_DATA=<OLD_PPROF_VERIFY_DATA> \
    PPROF_VERIFY_DATA=<PPROF_VERIFY_DATA> \
    RUN_ENV=<RUN_ENV>
COPY main probe.sh ./
ENTRYPOINT ["./main"]
